# Copyright (C) CampusIoT,  - All Rights Reserved
# Written by CampusIoT Dev Team, 2016-2018

version: "2"

services:

  # nodered:
  #   extends:
  #     file: nodered.yml
  #     service: nodered
  #   links:
  #     - influxdb:influxdb

  influxdb:
    extends:
      file: influxdb.yml
      service: influxdb

  grafana:
    extends:
      file: grafana.yml
      service: grafana
    links:
      - influxdb:influxdb

  python-backend:
    extends:
      file: python-backend.yml
      service: python-backend
    links:
      - influxdb:influxdb

  nginx:
    extends:
      file: nginx.yml
      service: nginx
    links:
     - python-backend:python-backend
     - grafana:grafana
