version: "2"

services:

  influxdb:
    extends:
      file: influxdb.yml
      service: influxdb

  grafana:
    extends:
      file: grafana.yml
      service: grafana
    depends_on:
      - influxdb

  python-backend:
    extends:
      file: python-backend.yml
      service: python-backend
    depends_on:
      - influxdb

  nginx:
    extends:
      file: nginx.yml
      service: nginx
    depends_on:
     - python-backend
     - grafana
