version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configuration/nginx/nginx.conf:/etc/nginx/conf.d/default.conf