{
 "title": "Mesure Carte 1",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "deviceName", "label": "Nom de la carte", "query": "\t6f047dfca4697d90" },
   { "name": "appName", "label": "Nom d'application", "query": "220" }
  ]
 },
 "panels": [
  {
   "title": "Quantité particule fine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quantités avec les valeurs récupérées",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "u/dL" } },
     "targets": [
      {
       "query": "t1 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_0_3\")\nt2 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_0_5\")\nt3 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_1_0\")\nt4 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_2_5\")\nt5 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_5_0\")\nt6 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_10\")\nunion(tables: [t1,t2,t3,t4,t5,t6])"
      }
     ]
    },
    {
     "title": "Quantités sans valeurs récupérées",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "u/dL" } },
     "targets": [
      {
       "query": "t1 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_0_3\" and r.recovery==\"false\")\nt2 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_0_5\" and r.recovery==\"false\")\nt3 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_1_0\" and r.recovery==\"false\")\nt4 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_2_5\" and r.recovery==\"false\")\nt5 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_5_0\" and r.recovery==\"false\")\nt6 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"q_pms_10\" and r.recovery==\"false\")\nunion(tables: [t1,t2,t3,t4,t5,t6])"
      }
     ]
    }
   ]
  },
  {
   "title": "Concentration particule fine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Concentrations avec les valeurs récupérées",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "query": "t1 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"c_pms_1_0\")\nt2 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"c_pms_2_5\")\nt3 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"c_pms_10\")\nunion(tables: [t1,t2,t3])"
      }
     ]
    },
    {
     "title": "Concentration sans valeurs récupérées",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "query": "t1 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"c_pms_1_0\" and r.recovery==\"false\")\nt2 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"c_pms_2_5\" and r.recovery==\"false\")\nt3 = from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"c_pms_10\" and r.recovery==\"false\")\nunion(tables: [t1,t2,t3])"
      }
     ]
    }
   ]
  },
  {
   "title": "Température et Humidité",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Humidité avec les valeurs récupérées",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"humidity\")\n"
      }
     ]
    },
    {
     "title": "Température avec les valeurs récupérées",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"temperature\")\n"
      }
     ]
    },
    {
     "title": "Humidité sans valeurs récupérées",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"humidity\" and r.recovery==\"false\")\n"
      }
     ]
    },
    {
     "title": "Température sans valeurs récupérées",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}\" and r._field == \"temperature\" and r.recovery==\"false\")\n"
      }
     ]
    }
   ]
  }
 ]
}