{
 "title": "Network Health 1",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "deviceName", "label": "Nom de la carte", "query": "6f047dfca4697d90" },
   { "name": "appName", "label": "Nom d'application", "query": "220" }
  ]
 },
 "panels": [
  {
   "title": "Nombre de paquet perdus (7 derniers jours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}:network-health-rec-los\" and r._field == \"nb_loss\")\n    |> sum()"
    }
   ]
  },
  {
   "title": "Pourcentage de paquet récupérés",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}:network-health-rec-los\")\n    |> sum()\n    |> pivot(rowKey: [\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> map(fn: (r) => ({r with\n            _value: if r.nb_loss == 0 or not exists r.nb_loss then \n                0.0\n            else \n                float(v: r.nb_recovery) / float(v: r.nb_loss) * 100.0\n        }),\n    )\n    |> drop(columns: [\"nb_loss\",\"nb_recovery\"])\n    "
    }
   ]
  },
  {
   "title": "Dernier Spreading Factor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air-quality\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"${deviceName}@${appName}:network-health-sf\" and r._field == \"spreading_factor\")\n"
    }
   ]
  }
 ]
}